
#20170823建表语句 黄成康

#OBJECT_MAXSN 流水号配置表
#CUSTOMER_INFO 客户信息表
#CUSTOMER_RELATIVE 客户关系关联表
#IND_INFO 客户详情表
#CUSTOMER_BELONG 客户归属表
#BUSINESS_APPLY 业务申请详情表
#BUSINESS_APPROVE 业务审详情批表
#BUSINESS_CONTRACT 业务合同详情表
#BUSINESS_PUTOUT 业务放款详情表
#BUSINESS_DUEBILL 借据详情表
#BUSINESS_RETURNPLAN 还款计划表
#BUSINESS_WASTEBOOK 还款流水表
#BUSINESS_TYPE 产品配置表
#BANLANCE_APPLY 额度申请表
#APPROVE_POOL 业务审批任务池
#TASK_TASKPOOL 放款任务审批池
#TASK_APPLYLOG 放款任务审批日志表
#SERVICE_SETUP 服务设置表
#TASK_APPROVE_RESULT 放款申请审批结果表
#SYSTEM_SETUP 业务系统设置


drop table if exists OBJECT_MAXSN;
create table if not exists  OBJECT_MAXSN  (
TableName VARCHAR(50) COMMENT  '表名',
ColumnName VARCHAR(50) COMMENT  '字段名',
MaxSerialNo VARCHAR(32) COMMENT  '当前最大流水号',
DateFmt VARCHAR(32) COMMENT  '日期格式',
NoFmt VARCHAR(20) COMMENT  '数字序列格式',
UNIQUE KEY OBJECT_MAXSN_INDEX1 (TableName,ColumnName)
) ENGINE=INNODB COMMENT '流水号配置表';

drop table if exists CUSTOMER_RELATIVE;
create table if not exists CUSTOMER_RELATIVE(
	CUSTOMERID VARCHAR(40) COMMENT '用户编号',
	RELATIONSHIP VARCHAR(18) COMMENT '关联关系',
	CUSTOMERNAME VARCHAR(80) COMMENT '家族成员姓名',
	CERTTYPE VARCHAR(18) COMMENT '证件类型',
	CERTID VARCHAR(32) COMMENT '证件号码',
	TELEPHONE VARCHAR(32) COMMENT '联系电话',
	SEX VARCHAR(18) COMMENT '性别',
	BIRTHDAY VARCHAR(10) COMMENT '出生日期',
	FAMILYADD VARCHAR(200) COMMENT '家庭住址',
	FAMILYZIP VARCHAR(32) COMMENT '住址邮编',
	EFFSTATUS VARCHAR(1) COMMENT '是否有效',
	INPUTORGID VARCHAR(80) COMMENT '登记机构编号',
	INPUTUSERID VARCHAR(80) COMMENT '登记人编号',
	INPUTDATE VARCHAR(10) COMMENT '登记日期',
	UPDATEDATE VARCHAR(10) COMMENT '更新日期',
	REMARK VARCHAR(200) COMMENT '备注',
	primary key(CUSTOMERID,RELATIONSHIP)
) ENGINE=INNODB COMMENT '客户关联表';

drop table if exists CUSTOMER_INFO;
create table if not exists CUSTOMER_INFO (
	CUSTOMERID VARCHAR(40) COMMENT'客户编号',
	CUSTOMERNAME VARCHAR(80) COMMENT'客户名称',
	CUSTOMERTYPE VARCHAR(20) COMMENT'客户类型',
	CERTTYPE VARCHAR(20) COMMENT'证件类型',
	CERTID VARCHAR(40) COMMENT'证件号码',
	INPUTORGID VARCHAR(32) COMMENT'登记机构',
	INPUTUSERID VARCHAR(32) COMMENT'登记人',
	INPUTDATE VARCHAR(10) COMMENT'登记日期',
	REMARK VARCHAR(250) COMMENT'备注',
	STATUS VARCHAR(20) COMMENT'认定状态',
	CHANNEL VARCHAR(18) COMMENT'来源渠道',
	ISOPEN int(2) COMMENT'是否已开户',
	primary key(CUSTOMERID)

) ENGINE=INNODB COMMENT '客户信息表';


drop table if exists IND_INFO;
create table if not exists  IND_INFO (
	CUSTOMERID VARCHAR(40) COMMENT'客户编号',
	FULLNAME VARCHAR(80) COMMENT'姓名',
	SEX VARCHAR(18) COMMENT'性别',
	BIRTHDAY VARCHAR(10) COMMENT'出生日期',
	CERTTYPE VARCHAR(18) COMMENT'证件类型',
	CERTID VARCHAR(32) COMMENT'证件号码',
	COUNTRY VARCHAR(18) COMMENT'国家',
	NATIONALITY VARCHAR(18) COMMENT'民族',
	NATIVEPLACE VARCHAR(200) COMMENT'户籍地址',
	POLITICALFACE VARCHAR(18) COMMENT'政治面貌',
	MARRIAGE VARCHAR(18) COMMENT'婚姻状况',
	RELATIVETYPE VARCHAR(200) COMMENT'联系方式',
	FAMILYADD VARCHAR(200) COMMENT'居住地址',
	FAMILYZIP VARCHAR(32) COMMENT'居住地址邮编',
	EMAILADD VARCHAR(80) COMMENT'电子邮箱',
	FAMILYTEL VARCHAR(32) COMMENT'住宅电话',
	MOBILETELEPHONE VARCHAR(32) COMMENT'手机号码',
	UNITKIND VARCHAR(18) COMMENT'单位所属行业',
	WORKCORP VARCHAR(80) COMMENT'单位名称',
	EMPRPROP VARCHAR(50) COMMENT'单位性质',
	WORKADD VARCHAR(200) COMMENT'单位地址',
	WORKTEL VARCHAR(32) COMMENT'单位电话',
	OCCUPATION VARCHAR(18) COMMENT'职业',
	POSITION VARCHAR(18) COMMENT'职称',
	EMPLOYRECORD VARCHAR(200) COMMENT'工作履历',
	EDURECORD VARCHAR(200) COMMENT'毕业学校(取得最高学历)',
	EDUEXPERIENCE VARCHAR(18) COMMENT'最高学历',
	EDUDEGREE VARCHAR(18) COMMENT'最高学位',
	GRADUATEYEAR VARCHAR(10) COMMENT'毕业年份',
	INTRO VARCHAR(200) COMMENT'个人情况简介',
	SELFMONTHINCOME double(24,6) COMMENT'个人月收入',
	FAMILYMONTHINCOME double(24,6) COMMENT'家庭年收入',
	INCOMESOURCE VARCHAR(200) COMMENT'收入来源',
	POPULATION int(2) COMMENT'家庭人口数',
	REGIONALISM VARCHAR(18) COMMENT'所属行政区域',
	STAFF VARCHAR(18) COMMENT'是否本行员工',
	COMMADD VARCHAR(200) COMMENT'通讯地址',
	COMMZIP VARCHAR(10) COMMENT'通讯地址邮编',
	NATIVEADD VARCHAR(200) COMMENT'户籍地址',
	WORKZIP VARCHAR(10) COMMENT'单位地址邮编',
	HEADSHIP VARCHAR(18) COMMENT'职务',
	WORKBEGINDATE VARCHAR(10) COMMENT'本单位工作起始日',
	YEARINCOME double(24,6) COMMENT'个人年收入',
	FAMILYSTATUS VARCHAR(18) COMMENT'居住状况',
	TEMPSAVEFLAG VARCHAR(18) COMMENT'暂存标志',
	POLICESTATION VARCHAR(80) COMMENT'户籍所在地派出所',
	DISTRICT VARCHAR(32) COMMENT'行政区划',
	CONTACTNAME VARCHAR(30) COMMENT'联系人姓名',
	CONTACTRELATION VARCHAR(80) COMMENT'联系人关系',
	CONTACTMETHOD VARCHAR(32) COMMENT'联系方式',
	FAMILYYEAR VARCHAR(3) COMMENT'居住年限',
	INPUTORGID VARCHAR(32) COMMENT'登记单位',
	INPUTUSERID VARCHAR(32) COMMENT'登记人',
	INPUTDATE VARCHAR(32) COMMENT'登记日期',
	UPDATEDATE VARCHAR(32) COMMENT'更新日期',
	UPDATEORGID VARCHAR(32) COMMENT'更新机构编号',
	UPDATEUSERID VARCHAR(32) COMMENT'更新用户编号',
	REMARK VARCHAR(200) COMMENT'备注',
	primary key(CUSTOMERID)

) ENGINE=INNODB COMMENT '客户详情表';

drop table if exists CUSTOMER_BELONG;
create table if not exists  CUSTOMER_BELONG (
	CUSTOMERID VARCHAR(40) COMMENT'客户编号',
	ORGID VARCHAR(40) COMMENT'所属机构',
	USERID VARCHAR(40) COMMENT'用户编号',
	BELONGATTRIBUTE1 VARCHAR(80) COMMENT'客户主办权',
	BELONGATTRIBUTE2 VARCHAR(80) COMMENT'信息查看权',
	BELONGATTRIBUTE3 VARCHAR(80) COMMENT'信息维护权',
	BELONGATTRIBUTE4 VARCHAR(80) COMMENT'业务申办权',
	INPUTUSERID VARCHAR(80) COMMENT'输入用户编号',
	INPUTORGID VARCHAR(40) COMMENT'输入机构编号',
	INPUTDATE VARCHAR(32) COMMENT'输入日期',
	UPDATEDATE VARCHAR(32) COMMENT'更新日期',
	REMARK VARCHAR(250) COMMENT'备注',
	primary key(CUSTOMERID)

) ENGINE=INNODB COMMENT '客户归属表';


drop table if exists BALANCE_APPLY;
create table if not exists  BALANCE_APPLY (
	SERIALNO VARCHAR(40) COMMENT'流水号',
	CUSTOMERID VARCHAR(40) COMMENT'客户编号',
	CUSTOMERNAME VARCHAR(80) COMMENT'客户名称',
	BUSINESSTYPE VARCHAR(40) COMMENT'业务类型',
	APPLYAMOUNT double(24,6) COMMENT'申请额度',
	APPLYDATE VARCHAR(20) COMMENT'申请日期',
	APPLYSOURCE VARCHAR(20) COMMENT'申请来源',
	COMACCOUNTNOBANKNO VARCHAR(32) COMMENT'收款账号银行行号',
	COMACCOUNTNOBANKNAME VARCHAR(32) COMMENT'收款账号银行行名',
	COMACCOUNTNO VARCHAR(32) COMMENT'收款账号',
	COMACCOUNTNONAME VARCHAR(32) COMMENT'收款账号姓名',
	PAYACCOUNTNOBANKNO VARCHAR(32) COMMENT'还款账号银行行号',
	PAYACCOUNTNOBANKNAME VARCHAR(20) COMMENT'还款账号银行行名',
	PAYACCOUNTNO VARCHAR(32) COMMENT'还款账号',
	PAYACCOUNTNONAME VARCHAR(32) COMMENT'还款账号姓名',
	BALANCECONTRACTID VARCHAR(40) COMMENT'合同文件名',
	APPLYSTATUS VARCHAR(20) COMMENT'申请状态',
	INPUTORGID VARCHAR(32) COMMENT'登记机构',
	INPUTUSERID VARCHAR(32) COMMENT'登记人',
	INPUTDATE VARCHAR(20) COMMENT'登记日期',
	UPDATEORGID VARCHAR(32) COMMENT'更新机构',
	UPDATEUSERID VARCHAR(32) COMMENT'更新人',
	UPDATEDATE VARCHAR(20) COMMENT'更新日期',
	REMARK VARCHAR(250) COMMENT'备注',
	primary key(SERIALNO)
) ENGINE=INNODB COMMENT '额度申请表';

drop table if exists BUSINESS_APPLY;
create table if not exists  BUSINESS_APPLY (
	SERIALNO VARCHAR(40) COMMENT'申请流水号字段',
	RELATIVESERIALNO VARCHAR(32) COMMENT'关联流水号字段（额度申请流水）',
	OCCURDATE VARCHAR(10) COMMENT'发生日期',
	CUSTOMERID VARCHAR(32) COMMENT'客户编号',
	CUSTOMERNAME VARCHAR(80) COMMENT'客户名称',
	BUSINESSTYPE VARCHAR(18) COMMENT'业务品种',
	BUSINESSSUBTYPE VARCHAR(18) COMMENT'业务子类型',
	OCCURTYPE VARCHAR(18) COMMENT'发生类型',
	APPLYTYPE VARCHAR(18) COMMENT'申请类型',
	BUSINESSCURRENCY VARCHAR(18) COMMENT'业务币种',
	BUSINESSSUM double(24,6) COMMENT'名义金额',
	TIMELIMIT int(4) COMMENT'贷款期限',
	TIMELIMITUNIT VARCHAR(18) COMMENT'贷款期限单位',
	TERMYEAR int(2) COMMENT'期限年',
	TERMMONTH int(2) COMMENT'期限月',
	TERMDAY int(2) COMMENT'期限日',
	BASERATETYPE VARCHAR(18) COMMENT'基准利率类型',
	BASERATE double(10,6) COMMENT'基准年利率',
	RATEFLOATTYPE VARCHAR(18) COMMENT'利率浮动方式',
	RATEFLOAT double(10,6) COMMENT'浮动率/点',
	BUSINESSRATE double(10,6) COMMENT'执行月利率',
	EXECUTEYEARRATE double(10,6) COMMENT'执行年利率',
	ADJUSTRATETYPE VARCHAR(18) COMMENT'利率调整方式',
	ADJUSTRATETERM VARCHAR(18) COMMENT'利率调整日月数',
	RATEADJUSTCYC VARCHAR(18) COMMENT'利率调整周期',
	FINERATETYPE VARCHAR(18) COMMENT'罚息利率类型',
	FINERATE double(10,6) COMMENT'罚息利率(‰)',
	PURPOSE VARCHAR(200) COMMENT'用途/理由',
	CORPUSPAYMETHOD VARCHAR(18) COMMENT'还款方式',
	PAYMENTTYPE VARCHAR(18) COMMENT'付款方式',
	CUSTOMERBELONG VARCHAR(20) COMMENT'客户所属人',
	VOUCHTYPE VARCHAR(10) COMMENT'担保方式',
	PLATFORMFEERATE double(24,6) COMMENT'平台费比例',
	PLATFORMFEE double(24,6) COMMENT'平台费',
	BUSINESSINSURANCEAMOUNT double(24,6) COMMENT'商业险保单金额',
	SALIAMOUNT double(24,6) COMMENT'车船税/交强险金额',
	BALANCEAPPLYDATE VARCHAR(32) COMMENT'额度申请日期',
	CARNO VARCHAR(32) COMMENT'车的唯一标识号码',
	COMACCOUNTNOBANKNO VARCHAR(32) COMMENT'收款账号银行行号',
	COMACCOUNTNOBANKNAME VARCHAR(32) COMMENT'收款账号银行行名',
	COMACCOUNTNO VARCHAR(32) COMMENT'收款账号',
	COMACCOUNTNONAME VARCHAR(32) COMMENT'收款账号姓名',
	PAYACCOUNTNOBANKNO VARCHAR(32) COMMENT'还款账号银行行号',
	PAYACCOUNTNOBANKNAME VARCHAR(20) COMMENT'还款账号银行行名',
	PAYACCOUNTNO VARCHAR(32) COMMENT'还款账号',
	PAYACCOUNTNONAME VARCHAR(32) COMMENT'还款账号姓名',
	STATUS VARCHAR(10) COMMENT'申请状态',
	OPERATEORGID VARCHAR(32) COMMENT'经办机构',
	OPERATEUSERID VARCHAR(32) COMMENT'经办人',
	OPERATEDATE VARCHAR(32) COMMENT'经办日期',
	INPUTORGID VARCHAR(32) COMMENT'登记机构',
	INPUTUSERID VARCHAR(32) COMMENT'登记人',
	INPUTDATE VARCHAR(32) COMMENT'登记日期',
	UPDATEDATE VARCHAR(32) COMMENT'更新日期',
	REMARK VARCHAR(200) COMMENT'备注',
	primary key(SERIALNO)
) ENGINE=INNODB COMMENT '业务申请表';


drop table if exists BUSINESS_APPROVE;
create table if not exists  BUSINESS_APPROVE (
	SERIALNO VARCHAR(40) COMMENT '申请流水号字段',
	RELATIVESERIALNO VARCHAR(32) COMMENT '关联流水号字段（申请流水）',
	OCCURDATE VARCHAR(10) COMMENT '发生日期',
	CUSTOMERID VARCHAR(32) COMMENT '客户编号',
	CUSTOMERNAME VARCHAR(80) COMMENT '客户名称',
	BUSINESSTYPE VARCHAR(18) COMMENT '业务品种',
	BUSINESSSUBTYPE VARCHAR(18) COMMENT '业务子类型',
	OCCURTYPE VARCHAR(18) COMMENT '发生类型',
	APPLYTYPE VARCHAR(18) COMMENT '申请类型',
	BUSINESSCURRENCY VARCHAR(18) COMMENT '业务币种',
	BUSINESSSUM double(24,6) COMMENT '名义金额',
	TIMELIMIT int(4) COMMENT '贷款期限',
	TIMELIMITUNIT VARCHAR(18) COMMENT '贷款期限单位',
	TERMYEAR int(2) COMMENT '期限年',
	TERMMONTH int(2) COMMENT '期限月',
	TERMDAY int(2) COMMENT '期限日',
	BASERATETYPE VARCHAR(18) COMMENT '基准利率类型',
	BASERATE double(10,6) COMMENT '基准年利率',
	RATEFLOATTYPE VARCHAR(18) COMMENT '利率浮动方式',
	RATEFLOAT double(10,6) COMMENT '浮动率/点',
	BUSINESSRATE double(10,6) COMMENT '执行月利率',
	EXECUTEYEARRATE double(10,6) COMMENT '执行年利率',
	ADJUSTRATETYPE VARCHAR(18) COMMENT '利率调整方式',
	ADJUSTRATETERM VARCHAR(18) COMMENT '利率调整日月数',
	RATEADJUSTCYC VARCHAR(18) COMMENT '利率调整周期',
	FINERATETYPE VARCHAR(18) COMMENT '罚息利率类型',
	FINERATE double(10,6) COMMENT '罚息利率(‰)',
	PURPOSE VARCHAR(200) COMMENT '用途/理由',
	CORPUSPAYMETHOD VARCHAR(18) COMMENT '还款方式',
	PAYMENTTYPE VARCHAR(18) COMMENT '付款方式',
	CUSTOMERBELONG VARCHAR(20) COMMENT '客户所属人',
	VOUCHTYPE VARCHAR(10) COMMENT '担保方式',
	PLATFORMFEERATE double(24,6) COMMENT '平台费比例',
	PLATFORMFEE double(24,6) COMMENT '平台费',
	BUSINESSINSURANCEAMOUNT double(24,6) COMMENT '商业险保单金额',
	SALIAMOUNT double(24,6) COMMENT '车船税/交强险金额',
	BALANCEAPPLYDATE VARCHAR(32) COMMENT '额度申请日期',
	CARNO VARCHAR(32) COMMENT '车的唯一标识号码',
	COMACCOUNTNOBANKNO VARCHAR(32) COMMENT '收款账号银行行号',
	COMACCOUNTNOBANKNAME VARCHAR(32) COMMENT '收款账号银行行名',
	COMACCOUNTNO VARCHAR(32) COMMENT '收款账号',
	COMACCOUNTNONAME VARCHAR(32) COMMENT '收款账号姓名',
	PAYACCOUNTNOBANKNO VARCHAR(32) COMMENT '还款账号银行行号',
	PAYACCOUNTNOBANKNAME VARCHAR(20) COMMENT '还款账号银行行名',
	PAYACCOUNTNO VARCHAR(32) COMMENT '还款账号',
	PAYACCOUNTNONAME VARCHAR(32) COMMENT '还款账号姓名',
	STATUS VARCHAR(10) COMMENT '审批状态',
	OPERATEORGID VARCHAR(32) COMMENT '经办机构',
	OPERATEUSERID VARCHAR(32) COMMENT '经办人',
	OPERATEDATE VARCHAR(32) COMMENT '经办日期',
	INPUTORGID VARCHAR(32) COMMENT '登记机构',
	INPUTUSERID VARCHAR(32) COMMENT '登记人',
	INPUTDATE VARCHAR(32) COMMENT '登记日期',
	UPDATEDATE VARCHAR(32) COMMENT '更新日期',
	REMARK VARCHAR(200) COMMENT '备注',
	primary key(SERIALNO)
) ENGINE=INNODB COMMENT '业务审批表';


drop table if exists APPROVE_POOL;
create table if not exists  APPROVE_POOL (
	SERIALNO VARCHAR(40) COMMENT '审批任务流水号字段',
	APPLYSERIALNO VARCHAR(32) COMMENT '申请流水号',
	APPROVESERIALNO VARCHAR(32) COMMENT '审批流水号',
	CUSTOMERID VARCHAR(32) COMMENT '客户编号',
	CUSTOMERNAME VARCHAR(80) COMMENT '客户名称',
	BUSINESSTYPE VARCHAR(18) COMMENT '业务品种',
	STATUS VARCHAR(20) COMMENT '处理状态',
	REMARK VARCHAR(200) COMMENT '审批备注',
	CUSTOMERBELONG VARCHAR(20) COMMENT '申请归属用户',
	OPERATEORGID VARCHAR(32) COMMENT '经办机构',
	OPERATEUSERID VARCHAR(32) COMMENT '经办人',
	OPERATEDATE VARCHAR(32) COMMENT '经办日期',
	INPUTORGID VARCHAR(32) COMMENT '登记机构',
	INPUTUSERID VARCHAR(32) COMMENT '登记人',
	INPUTDATE VARCHAR(32) COMMENT '登记日期',
	primary key(SERIALNO)

) ENGINE=INNODB COMMENT '业务审批池';


drop table if exists BUSINESS_CONTRACT;
create table if not exists  BUSINESS_CONTRACT (
	SERIALNO VARCHAR(40) COMMENT '申请流水号字段',
	RELATIVESERIALNO VARCHAR(32) COMMENT '关联流水号字段',
	CUSTOMERID VARCHAR(32) COMMENT '客户编号',
	CUSTOMERNAME VARCHAR(80) COMMENT '客户名称',
	BUSINESSTYPE VARCHAR(18) COMMENT '业务品种',
	OCCURTYPE VARCHAR(18) COMMENT '发生类型',
	BUSINESSCURRENCY VARCHAR(18) COMMENT '业务币种',
	BUSINESSSUM double(24,6) COMMENT '合同金额',
	TERMYEAR int(2) COMMENT '期限年',
	TERMMONTH int(2) COMMENT '期限月',
	TERMDAY int(2) COMMENT '期限日',
	BASERATETYPE VARCHAR(18) COMMENT '基准利率类型',
	BASERATE double(10,6) COMMENT '基准年利率',
	RATEFLOATTYPE VARCHAR(18) COMMENT '利率浮动方式',
	RATEFLOAT double(10,6) COMMENT '浮动率/点',
	BUSINESSRATE double(10,6) COMMENT '执行月利率',
	BUSINESYEARSRATE double(10,6) COMMENT '执行年利率',
	DEDUCTDATE VARCHAR(10) COMMENT '还款日期',
	PURPOSE VARCHAR(200) COMMENT '用途/理由',
	CORPUSPAYMETHOD VARCHAR(18) COMMENT '还款方式',
	APPLYTYPE VARCHAR(18) COMMENT '申请类型',
	PAYMENTTYPE VARCHAR(18) COMMENT '付款方式',
	TIMELIMIT int(10) COMMENT '贷款期限',
	TIMELIMITUNIT VARCHAR(18) COMMENT '贷款期限单位',
	CUSTOMERBELONG VARCHAR(20) COMMENT '客户所属人',
	ADJUSTRATETYPE VARCHAR(18) COMMENT '利率调整方式',
	ADJUSTRATETERM VARCHAR(18) COMMENT '利率调整日月数',
	RATEADJUSTCYC VARCHAR(18) COMMENT '利率调整周期',
	FINERATETYPE VARCHAR(18) COMMENT '罚息利率类型',
	FINERATE double(10,6) COMMENT '罚息利率(‰)',
	BALANCE double(24,6) COMMENT '总余额',
	OVERDUEBALANCE double(24,6) COMMENT '逾期/垫款金额',
	DULLBALANCE double(24,6) COMMENT '呆滞余额',
	BADBALANCE double(24,6) COMMENT '呆账余额',
	FINEBALANCE1 double(24,6) COMMENT '本金罚息',
	FINEBALANCE2 double(24,6) COMMENT '利息罚息',
	TABALANCE VARCHAR(30) COMMENT '分期业务欠本金',
	TAINTERESTBALANCE VARCHAR(30) COMMENT '分期业务欠利息',
	TATIMES VARCHAR(32) COMMENT '累计欠款期数',
	LCATIMES VARCHAR(32) COMMENT '连续欠款期数',
	EXTENDTIMES VARCHAR(32) COMMENT '展期次数',
	FINISHTYPE VARCHAR(18) COMMENT '终结类型',
	FINISHDATE VARCHAR(10) COMMENT '终结日期',
	OVERDUEDATE VARCHAR(10) COMMENT '逾期日期',
	OVERDUEDAYS int(4) COMMENT '逾期天数',
	VOUCHTYPE VARCHAR(10) COMMENT '担保方式',
	PLATFORMFEERATE double(24,6) COMMENT '平台费比例',
	PLATFORMFEE double(24,6) COMMENT '平台费',
	COMACCOUNTNOBANKNO VARCHAR(32) COMMENT '收款账号银行行号',
	COMACCOUNTNOBANKNAME VARCHAR(32) COMMENT '收款账号银行行名',
	COMACCOUNTNO VARCHAR(32) COMMENT '收款账号',
	COMACCOUNTNONAME VARCHAR(32) COMMENT '收款账号姓名',
	PAYACCOUNTNOBANKNO VARCHAR(32) COMMENT '还款账号银行行号',
	PAYACCOUNTNOBANKNAME VARCHAR(32) COMMENT '还款账号银行行名',
	PAYACCOUNTNO VARCHAR(32) COMMENT '还款账号',
	PAYACCOUNTNONAME VARCHAR(32) COMMENT '还款账号姓名',
	CONTRACTSTATUS VARCHAR(32) COMMENT '合同状态',
	OPERATEORGID VARCHAR(32) COMMENT '经办机构',
	OPERATEUSERID VARCHAR(32) COMMENT '经办人',
	OPERATEDATE VARCHAR(32) COMMENT '经办日期',
	INPUTORGID VARCHAR(32) COMMENT '登记机构',
	INPUTUSERID VARCHAR(32) COMMENT '登记人',
	INPUTDATE VARCHAR(32) COMMENT '登记日期',
	REMARK VARCHAR(200) COMMENT '备注',
	primary key(SERIALNO)

) ENGINE=INNODB COMMENT '业务合同详情';



drop table if exists BUSINESS_PUTOUT;
create table if not exists  BUSINESS_PUTOUT (
	SERIALNO VARCHAR(40) COMMENT '申请流水号字段',
	RELATIVESERIALNO VARCHAR(32) COMMENT '关联流水号字段',
	CUSTOMERID VARCHAR(32) COMMENT '客户编号',
	CUSTOMERNAME VARCHAR(80) COMMENT '客户名称',
	BUSINESSTYPE VARCHAR(18) COMMENT '业务品种',
	OCCURTYPE VARCHAR(18) COMMENT '发生类型',
	BUSINESSCURRENCY VARCHAR(18) COMMENT '业务币种',
	BUSINESSSUM double(24,6) COMMENT '合同金额',
	PUTOUTSUM double(24,6) COMMENT '放款金额',
	ACTUALPUTOUTSUM double(24,6) COMMENT '实际放款金额',
	TERMYEAR int(2) COMMENT '期限年',
	TERMMONTH int(2) COMMENT '期限月',
	TERMDAY int(2) COMMENT '期限日',
	PUTOUTDATE VARCHAR(10) COMMENT '起贷日',
	MATURITY VARCHAR(10) COMMENT '到期日',
	BASERATETYPE VARCHAR(18) COMMENT '基准利率类型',
	BASERATE double(10,6) COMMENT '基准年利率',
	RATEFLOATTYPE VARCHAR(18) COMMENT '利率浮动方式',
	RATEFLOAT double(10,6) COMMENT '浮动率/点',
	BUSINESSRATE double(10,6) COMMENT '执行月利率',
	BUSINESYEARSRATE double(10,6) COMMENT '执行年利率',
	ADJUSTRATETYPE VARCHAR(18) COMMENT '利率调整方式',
	ADJUSTRATETERM VARCHAR(18) COMMENT '利率调整日月数',
	RATEADJUSTCYC VARCHAR(18) COMMENT '利率调整周期',
	FINERATETYPE VARCHAR(18) COMMENT '罚息利率类型',
	FINERATE double(10,6) COMMENT '罚息利率(‰)',
	APPLYTYPE VARCHAR(18) COMMENT '申请类型',
	PURPOSE VARCHAR(200) COMMENT '用途/理由',
	CORPUSPAYMETHOD VARCHAR(18) COMMENT '还款方式',
	DEDUCTDATE VARCHAR(10) COMMENT '还款日期',
	PAYMENTTYPE VARCHAR(18) COMMENT '付款方式',
	TIMELIMIT int(10) COMMENT '贷款期限',
	TIMELIMITUNIT VARCHAR(18) COMMENT '贷款期限单位',
	BALANCE double(24,6) COMMENT '总余额',
	DULLBALANCE double(24,6) COMMENT '呆滞余额',
	BADBALANCE double(24,6) COMMENT '呆账余额',
	FINEBALANCE1 double(24,6) COMMENT '本金罚息',
	FINEBALANCE2 double(24,6) COMMENT '利息罚息',
	FINISHTYPE VARCHAR(18) COMMENT '终结类型',
	FINISHDATE VARCHAR(10) COMMENT '终结日期',
	OVERDUEDATE VARCHAR(10) COMMENT '逾期日期',
	OVERDUEDAYS int(4) COMMENT '逾期天数',
	OVERDUEBALANCE double(24,6) COMMENT '逾期金额',
	VOUCHTYPE VARCHAR(10) COMMENT '担保方式',
	PLATFORMFEERATE double(24,6) COMMENT '平台费比例',
	PLATFORMFEE double(24,6) COMMENT '平台费',
	COMACCOUNTNOBANKNO VARCHAR(32) COMMENT '收款账号银行行号',
	COMACCOUNTNOBANKNAME VARCHAR(32) COMMENT '收款账号银行行名',
	COMACCOUNTNO VARCHAR(32) COMMENT '收款账号',
	COMACCOUNTNONAME VARCHAR(32) COMMENT '收款账号姓名',
	PAYACCOUNTNOBANKNO VARCHAR(32) COMMENT '还款账号银行行号',
	PAYACCOUNTNOBANKNAME VARCHAR(32) COMMENT '还款账号银行行名',
	PAYACCOUNTNO VARCHAR(32) COMMENT '还款账号',
	PAYACCOUNTNONAME VARCHAR(32) COMMENT '还款账号姓名',
	DUEBILLSERIALNO VARCHAR(32) COMMENT '借据号',
	PUTOUTSTATUS VARCHAR(10) COMMENT '放款状态',
	OPERATEORGID VARCHAR(32) COMMENT '经办机构',
	OPERATEUSERID VARCHAR(32) COMMENT '经办人',
	OPERATEDATE VARCHAR(32) COMMENT '经办日期',
	INPUTORGID VARCHAR(32) COMMENT '登记机构',
	INPUTUSERID VARCHAR(32) COMMENT '登记人',
	INPUTDATE VARCHAR(32) COMMENT '登记日期',
	REMARK VARCHAR(200) COMMENT '备注',
	primary key(SERIALNO)

) ENGINE=INNODB COMMENT '业务放款出账详情';


drop table if exists BUSINESS_DUEBILL;
create table if not exists  BUSINESS_DUEBILL (
	SERIALNO VARCHAR(40) COMMENT '流水号',
	PUTOUTSERIALNO VARCHAR(40) COMMENT '相关出账流水号',
	CONTRACTSERIALNO VARCHAR(40) COMMENT '相关合同流水号',
	CUSTOMERID VARCHAR(40) COMMENT '客户编号',
	CUSTOMERNAME VARCHAR(80) COMMENT '客户名称',
	BUSINESSTYPE VARCHAR(18) COMMENT '业务品种代码',
	BUSINESSSUBTYPE VARCHAR(20) COMMENT '业务品种子类型',
	BUSINESSSTATUS VARCHAR(20) COMMENT '业务形态',
	BUSINESSCURRENCY VARCHAR(20) COMMENT '币种',
	BUSINESSSUM double(24,6) COMMENT '借据金额',
	PUTOUTDATE VARCHAR(10) COMMENT '发放日期',
	MATURITY VARCHAR(10) COMMENT '到期日',
	ACTUALMATURITY VARCHAR(10) COMMENT '实际到期日',
	BUSINESSRATE double(24,10) COMMENT '月利率',
	EXECUTEYEARRATE double(10,6) COMMENT '执行年利率',
	TERMSFREQ VARCHAR(10) COMMENT '还款频率',
	BALANCE double(24,6) COMMENT '借据余额',
	NORMALBALANCE double(24,6) COMMENT '正常余额',
	OVERDUEBALANCE double(24,6) COMMENT '逾期余额',
	DULLBALANCE double(24,6) COMMENT '呆滞余额',
	BADBALANCE double(24,6) COMMENT '呆账余额',
	PENALTYAMT VARCHAR(30) COMMENT '罚息余额',
	INTERESTPENALTYAMT VARCHAR(30) COMMENT '复息余额',
	OVERDUEAMOUNT double(24,6) COMMENT '逾期金额',
	OVERDUEDATE VARCHAR(10) COMMENT '逾期日期',
	OVERDUEDAYS int(4) COMMENT '逾期天数',
	TABALANCE VARCHAR(30) COMMENT '分期业务欠本金',
	TAINTERESTBALANCE VARCHAR(30) COMMENT '分期业务欠利息',
	TATIMES VARCHAR(32) COMMENT '累计欠款期数',
	LCATIMES VARCHAR(32) COMMENT '连续欠款期数',
	EXTENDTIMES VARCHAR(32) COMMENT '展期次数',
	PAYBACKACCOUNT VARCHAR(40) COMMENT '还款帐号',
	FINISHTYPE VARCHAR(20) COMMENT '终结类型',
	FINISHDATE VARCHAR(10) COMMENT '终结日期',
	ACTUALTERMMONTH int(2) COMMENT '期限月',
	ACTUALTERMDAY int(2) COMMENT '期限年',
	BASERATETYPE VARCHAR(20) COMMENT '基准利率类型',
	BASERATE double(24,6) COMMENT '基准利率',
	RATEFLOATTYPE VARCHAR(20) COMMENT '利率浮动类型',
	RATEFLOAT double(24,6) COMMENT '利率浮动',
	PURPOSE VARCHAR(200) COMMENT '用途',
	ADJUSTRATETYPE VARCHAR(20) COMMENT '利率调整方式',
	ADJUSTRATETERM VARCHAR(20) COMMENT '利息调整月数',
	RATEADJUSTCYC VARCHAR(20) COMMENT '利率调整日期',
	DEDUCTDATE VARCHAR(10) COMMENT '扣款日期',
	PAYEDBALANCE double(24,6) COMMENT '还款金额',
	GRACEPERIOD int(10) COMMENT '还款宽限期',
	CLASSIFY4 VARCHAR(18) COMMENT '四级分类',
	CLASSIFYRESULT VARCHAR(18) COMMENT '五级分类结果',
	VOUCHTYPE VARCHAR(10) COMMENT '担保方式',
	OPERATEORGID VARCHAR(20) COMMENT '经办机构',
	OPERATEUSERID VARCHAR(20) COMMENT '经办人',
	INPUTORGID VARCHAR(20) COMMENT '登记机构',
	INPUTUSERID VARCHAR(20) COMMENT '登记人',
	INPUTDATE VARCHAR(20) COMMENT '登记日期',
	UPDATEDATE VARCHAR(20) COMMENT '更新日期',
	primary key(SERIALNO)

) ENGINE=INNODB COMMENT '业务借据详情表';

drop table if exists BUSINESS_RETURNPLAN;
create table if not exists  BUSINESS_RETURNPLAN (
	SERIALNO VARCHAR(40) COMMENT '流水号',
	BCSERIALNO VARCHAR(40) COMMENT '合同流水号',
	BDSERIALNO VARCHAR(40) COMMENT '关联借据流水号',
	CUSTOMERID VARCHAR(40) COMMENT '客户编号',
	CUSTOMERNAME VARCHAR(80) COMMENT '客户名称',
	RETURNPLANTYPE VARCHAR(10) COMMENT '还款计划类型',
	PERIODNO int(2) COMMENT '期次',
	PAYDATE VARCHAR(10) COMMENT '应还日期',
	INTEDATE VARCHAR(10) COMMENT '节假日及宽限期顺延后的还款日期',
	HOLIDAYINTEDATE VARCHAR(10) COMMENT '节假日顺延后的还款日',
	GRACEINTEDATE VARCHAR(10) COMMENT '宽限期顺延后的还款日期（开始计算罚息的日期）',
	CURRENCY VARCHAR(10) COMMENT '币种',
	PAYPRINCIPALAMT double(20,2) COMMENT '应还本金',
	ACTUALPAYPRINCIPALAMT double(20,2) COMMENT '实还本金 ',
	WAIVEPRINCIPALAMT double(20,2) COMMENT '减免本金金额',
	PRINCIPALBALANCE double(20,2) COMMENT '剩余本金余额',
	PAYINTERESTAMT double(20,2) COMMENT '应还利息',
	ACTUALPAYINTERESTAMT double(20,2) COMMENT '实还利息',
	WAIVEINTERESTAMT double(20,2) COMMENT '减免利息金额',
	PAYPRINCIPALPENALTYAMT double(20,2) COMMENT '应还本金罚息',
	ACTUALPAYPRINCIPALPENALTYAMT double(20,2) COMMENT '实还本金罚息',
	WAIVEPRINCIPALPENALTYAMT double(20,2) COMMENT '减免本金罚息',
	PAYINTERESTPENALTYAMT double(20,2) COMMENT '应还利息罚息',
	ACTUALPAYINTERESTPENALTYAMT double(20,2) COMMENT '实还利息罚息',
	WAIVEINTERESTPENALTYAMT double(20,2) COMMENT '减免利息罚息',
	STATUS VARCHAR(10) COMMENT '状态',
	FINISHDATE VARCHAR(10) COMMENT '结清日期（实际还款日期）',
	REMARK VARCHAR(400) COMMENT '备注',
	UPDATEDATE VARCHAR(20) COMMENT '更新日期',
	primary key(SERIALNO)

) ENGINE=INNODB COMMENT '还款计划表';


drop table if exists BUSINESS_WASTEBOOK;
create table if not exists  BUSINESS_WASTEBOOK (
	SERIALNO VARCHAR(20) COMMENT '交易流水号',
	BPSERIALNO VARCHAR(32) COMMENT '借据号',
	TRANSDATE VARCHAR(10) COMMENT '发生日期',
	OCCURTYPE VARCHAR(10) COMMENT '发生类型',
	ACTUALPAYPRINCIPAAMT double(24,6) COMMENT '本金',
	ACTUALPAYINTERESTAMT double(24,6) COMMENT '利息',
	ACTUALPAYPRINCIPALPENALTYAMT double(24,6) COMMENT '本金罚息',
	ACTUALPAYINTERESTPENALTYAMT double(24,6) COMMENT '复息',
	PREPAYPENALTYAMT double(24,6) COMMENT '违约金',
	INTERSTSUBSIDYAMT double(24,6) COMMENT '贴息金额',
	OTHERFEE double(24,6) COMMENT '其他费用（平台费等）',
	TERM int(2) COMMENT '还款期次',
	PAYACCOUNNO VARCHAR(40) COMMENT '还款账户账号',
	CHANNEL VARCHAR(20) COMMENT '渠道号',
	primary key(SERIALNO)

) ENGINE=INNODB COMMENT '还款流水表';


drop table if exists TASK_TASKPOOL;
create table if not exists  TASK_TASKPOOL (
	SERIALNO bigint(20) COMMENT '任务流水号',
	RELATIVESERIALNO VARCHAR(40) COMMENT '审批池流水号',
	CUSTOMERID VARCHAR(32) COMMENT '客户号',
	CUSTOMERNAME VARCHAR(80) COMMENT '客户姓名',
	BUSINESSTYPE VARCHAR(18) COMMENT '业务品种',
	BASERIALNO VARCHAR(40) COMMENT '申请流水号',
	BAPSERIALNO VARCHAR(40) COMMENT '批复流水号',
	OPERATESTATUS VARCHAR(10) COMMENT '处理状态：01-准备中 02-就绪 03-处理中 04-处理失败 00-处理成功',
	SETPCLASS VARCHAR(100) COMMENT '步骤记录',
	INPUTDATE VARCHAR(20) COMMENT '录入日期YYYY/MM/DD HH:MM:SS',
	UPDATEDATE VARCHAR(20) COMMENT '更新日期YYYY/MM/DD HH:MM:SS',
	TRANSDATE VARCHAR(10) COMMENT '交易日期',
	CHANNEL VARCHAR(20) COMMENT '渠道号',
	primary key(SERIALNO),
	KEY `IDX_TASKPOOL_OPERATESTATUS` (`OPERATESTATUS`) USING BTREE
) ENGINE=INNODB COMMENT '放款申请任务池';


drop table if exists TASK_APPLYLOG;
create table if not exists  TASK_APPLYLOG (
	SERIALNO VARCHAR(20) COMMENT '日志流水号',
	TPSERIALNO bigint(20) COMMENT '关联任务流水号',
	RELATIVESERIALNO VARCHAR(40) COMMENT '关联流水号',
	REQUESTCOUNT int(2) COMMENT '请求次数',
	TRANSCODE VARCHAR(20) COMMENT '交易代码',
	OPERATESTATUS VARCHAR(10) COMMENT '处理状态：00-处理成功 01-处理失败',
	BUSINESSSTATUS VARCHAR(10) COMMENT '业务状态：01-业务拒绝 00-业务通过',
	REQUESTMESSAGE text COMMENT '请求报文',
	RESPONSEMESSAGE text COMMENT '返回报文',
	RESPONSECODE VARCHAR(10) COMMENT '返回CODE',
	INPUTDATE VARCHAR(20) COMMENT '输入日期',
	UPDATEDATE VARCHAR(20) COMMENT '更新日期',
	primary key(SERIALNO)
) ENGINE=INNODB COMMENT '放款申请日志表';


drop table if exists SERVICE_SETUP;
create table if not exists  SERVICE_SETUP (
	SERVICEID VARCHAR(10) COMMENT 'ID',
	CHANNEL VARCHAR(32) COMMENT '渠道',
	BUSINESSTYPE VARCHAR(50) COMMENT '产品类型（多个用@分隔）',
	BUSINESSNAME VARCHAR(100) COMMENT '产品名称',
	STARTTIME int(2) COMMENT '系统开始运行时间（24小时制,小时区间）',
	ENDTIME int(2) COMMENT '系统结束运行时间（24小时制,小时区间）',
	SERVICEFLAG VARCHAR(10) COMMENT '任务或者服务开启标志',
	primary key(SERVICEID)
) ENGINE=INNODB COMMENT '服务控制表';


drop table if exists TASK_APPROVE_RESULT;
create table if not exists  TASK_APPROVE_RESULT (
	SERIALNO VARCHAR(32) COMMENT '审批结果流水号',
	TPSERIALNO VARCHAR(32) COMMENT '任务流水号',
	CUSTOMERNAME VARCHAR(32) COMMENT '客户姓名',
	CUSTOMERID VARCHAR(32) COMMENT '客户ID',
	BASERIALNO VARCHAR(32) COMMENT '申请流水号',
	BAPSERIALNO VARCHAR(32) COMMENT '审批流水号',
	BCSERIALNO VARCHAR(32) COMMENT '合同流水号',
	BPSERIALNO VARCHAR(32) COMMENT '出账流水号',
	BDSERIALNO VARCHAR(32) COMMENT '借据号',
	RESULTSTATUS VARCHAR(10) COMMENT '申请结果状态',
	RESPCODE VARCHAR(10) COMMENT '返回代码',
	RESPDESC VARCHAR(200) COMMENT '返回结果',
	BUSINESSTYPE VARCHAR(32) COMMENT '业务类型',
	CHANNEL VARCHAR(32) COMMENT '渠道号',
	INPUTDATE VARCHAR(10) COMMENT '输入日期',
	INPUTTIME VARCHAR(10) COMMENT '输入时间',
	UPDATEDATE VARCHAR(10) COMMENT '更新日期',
	UPDATETIME VARCHAR(10) COMMENT '更新时间',
	KEY `IDX_TASK_APPROVE_RESULT` (`BUSINESSTYPE`,`CHANNEL`) USING BTREE,
	primary key(SERIALNO)

) ENGINE=INNODB COMMENT '放款申请审批结果表';


drop table if exists BUSINESS_TYPE;
CREATE TABLE `BUSINESS_TYPE` (
  `TYPENO` varchar(32) NOT NULL DEFAULT '' COMMENT '产品编号',
  `SORTNO` varchar(32) DEFAULT NULL COMMENT '排序编号',
  `TYPENAME` varchar(80) DEFAULT NULL COMMENT '产品名称',
  `ATTRIBUTE1` varchar(50) DEFAULT NULL COMMENT '属性1',
  `ATTRIBUTE2` varchar(100) DEFAULT NULL COMMENT '属性2',
  `ATTRIBUTE3` varchar(200) DEFAULT NULL COMMENT '属性3',
  `LEASEHOLD` varchar(200) DEFAULT NULL COMMENT '产品期限（逗号分隔，支持多个）',
  `EXECUTEYEARRATE` int(10) DEFAULT NULL COMMENT '执行年利率',
  `BALANCETYPE` int(10) DEFAULT NULL COMMENT '额度类型（1:固定额度 2:可变额度）',
  `CREDITBALANCE` double(24,6) DEFAULT NULL COMMENT '授信额度',
  `PLATFORMFEE` double(24,6) DEFAULT NULL COMMENT '平台费',
  `ISHOLIDAYPOSTPONE` varchar(2) DEFAULT NULL COMMENT '是否节假日顺延',
  `ISALLOWANCE` varchar(2) DEFAULT NULL COMMENT '是否还款宽限期',
  `STATUS` varchar(32) DEFAULT NULL COMMENT '产品状态',
  `INPUTUSER` varchar(32) DEFAULT NULL COMMENT '登记人',
  `INPUTORG` varchar(32) DEFAULT NULL COMMENT '登记机构',
  `INPUTTIME` varchar(20) DEFAULT NULL COMMENT '登记时间',
  `UPDATEUSER` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATETIME` varchar(20) DEFAULT NULL COMMENT '更新时间',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`TYPENO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='产品类型配置表';


drop table if exists SYSTEM_SETUP;
create table if not exists  SYSTEM_SETUP (
	SYSTEMID	VARCHAR(10) COMMENT '系统ID',
	BUSINESSDATE	VARCHAR(10) COMMENT '业务日期 YYYY-MM-DD',
	BATCHFLAG	VARCHAR(1) COMMENT '日终批量总开关（0：关闭，1：开启）',
	TASKFLAG	VARCHAR(1) COMMENT '实时任务总开关（0：关闭，1：开启）',
	SERVICEFLAG	VARCHAR(1) COMMENT '接口服务总开关（0：关闭，1：开启）',
	primary key(SYSTEMID)
) ENGINE=INNODB COMMENT '系统设置表';



#清表脚本
truncate table CUSTOMER_INFO;
truncate table IND_INFO;
truncate table CUSTOMER_BELONG;

truncate table BUSINESS_APPLY;
truncate table BUSINESS_APPROVE;
truncate table BUSINESS_CONTRACT;
truncate table BUSINESS_PUTOUT;
truncate table BUSINESS_DUEBILL;
truncate table BUSINESS_RETURNPLAN;
truncate table BUSINESS_WASTEBOOK;
truncate table BALANCE_APPLY;

truncate table APPROVE_POOL;
truncate table TASK_TASKPOOL;
truncate table TASK_APPLYLOG;
truncate table TASK_APPROVE_RESULT;

#truncate table BUSINESS_TYPE;
#truncate table SERVICE_SETUP;
